### ISSUE TITLE
get number of Bytes as integer

### ISSUE THREAD

**Issue by inkrement** [gabrielelana/byte-units#10]
Is there a nice way to get the number of bytes?

I use the following up to now...
```php
(int) rtrim(\ByteUnits\parse('10 GiB')->format('B'), 'B')
```

**Comment by gabrielelana** [comment]
Nope, but we can expose the attribute [`$numberOfBytes`](https://github.com/gabrielelana/byte-units/blob/master/src/ByteUnits/System.php#L11) with a method `numberOfBytes()`

What do you think?

BTW: pull requests are welcome 😉

**Comment by inkrement** [comment]
So.. i added a pull request. Now it just returns the value as a string. Maybe we should convert it to an int before. what do you think about it?

**Comment by gabrielelana** [comment]
Absolutely, it should be an int 👍

**Comment by inkrement** [comment]
I reconsidered it and I think the string is even better. Although an integer would fit better on an semantic level the string-representation has the benefit that it can handle (theoretically) arbitrarily large integers. Ok, PHP_MAX_INT should be on modern 64bit machines 9223372036854775807, but in times of big data we should think even bigger and provide future-proofness. So, please accept my pull request.

**Comment by gabrielelana** [comment]
😂 Ok 😉

**Comment by gabrielelana** [comment]
@inkrement pushed a new release, be mind that I've renamed the method `numberOfBytes`

**Comment by inkrement** [comment]
thx ;)
