### ISSUE TITLE
Release new version every

### ISSUE THREAD

**Issue by northys** [gabrielelana/byte-units#14]
Hi @gabrielelana,

Can you please release new version on GitHub? You have merged a few pull requests since last release which forces us to use "dev-master" dependency in composer :(

Thank you!

**Comment by gabrielelana** [comment]
@northys Did you need compatibility with PHP >= 5.4 or can I require PHP >= 5.6? I would like to update few things

**Comment by gabrielelana** [comment]
@northys never mind I've managed to keep the compatibility pretty wide by removing `composer.lock`

**Comment by northys** [comment]
@gabrielelana we are currently using php 7.1 :) thank you for releasing new version
